### ISSUE TITLE
How to lazyload background images?

### ISSUE THREAD

**Issue by geochanto** [alvarotrigo/react-fullpage#122]
How can I lazyload background images in slides?

I came across a similar question on regular fullpage.js, and the answer was one can use the .active class to only render images for the active slide. This can be acceptable but can you suggest what would be the proper way to do this in react-fullpage? 

Also, any way to preload previous/next slide background images if/when the above starts working?

**Comment by alvarotrigo** [comment]
The lazy load option of fullpage.js only works for images and media elements. Background images are configured on CSS, therefore you'll have to deal with it in CSS.

> Also, any way to preload previous/next slide background images if/when the above starts working?

Sure! Not something that is provided by fullpage.js but you can easily achieve it by making use of the [fullpage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs):

```css
/* Preloading section 2 background when in section 1 */
.fp-viewing-section1 #section2{
   background-image: url('demo.gif');
}
```
