### ISSUE TITLE
Fullpage loads with delay, causing page to load two times

### ISSUE THREAD

**Issue by sumanthyedoti** [alvarotrigo/react-fullpage#187]
The entire page loads, when the react-fullpage is not in action yet, I can scroll the entire page as normal.
After 'fullpage' loads, it caused the page to load again. I have some animation on the hero section. The animation play again after fullpage comes into action. So page looking janky on load, it looks like the page is loading two times. 

How to solve this?

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by sumanthyedoti** [comment]
@alvarotrigo 
I am afraid I can't reproduce this. The page I used the library in, is very heavy and is in production. You can check the website here, [redd.in](http://redd.in/)

You can think of it from `afterRender` callback point-of-view. The page loads, the CSS animation in the Hero section plays again after the full-page is rendered.

I am thinking to use pre-loader until `afterRender` is triggered. Any workaround without doing that, please

**Comment by sumanthyedoti** [comment]
@alvarotrigo
I am afraid I can't reproduce this. The page I used the library in, is very heavy. 

You can think of it from `afterRender` callback point-of-view. The page loads, the CSS animation in the Hero section plays again after the full-page is rendered.

I am thinking to use pre-loader until `afterRender` is triggered. Any workaround without doing that, please

**Comment by alvarotrigo** [comment]
As you are loading the fullpage CSS file in your header, I would recommend you to us the class 'fp-enabled' in your `html` element.
This way you'll apply part of the css that gets applied when fullPage.js is enable, more specifically this part:

```css
html.fp-enabled,
.fp-enabled body {
    margin: 0;
    padding: 0;
    overflow:hidden;

    /*Avoid flicker on slides transitions for mobile phones #336 */
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
``` 


If you want go even further, you can also add this custom css in  your stylesheet to make your sections fullscreen before initialising fullpage:

```css
#fullpage, /* id used in your fullpage wrapper*/
.section, /* class used in your sections*/
body,
.fp-tableCell,  /* in case you want your content to be centered*/
html {
    height: 100%
}
```

The `.fp.tableCell` class gets added when using `verticalCentered:true` which is like this by default. If you plan to leave it, you can also include this by yourself before even initialising fulllpage.js, so you can wrap your sections content in it, for example:


```html
<div class="section">
    <div class="fp-tableCell">
        Content here 
    </div>
</div>
```
